version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/StreamAwesome"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Dependency"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
