name: Build StreamAwesome

on:
 workflow_dispatch:
 push:
 pull_request:
  types: [opened, synchronize, reopened]

env:
  FONTAWESOME_VERSION: "6.6.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Download FontAwesome ğŸ“¦
        run: .devcontainer/setup-fontawesome-free.sh
      
      - uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install and Build ğŸ”§
        working-directory: StreamAwesome
        run: |
          npm install
          npm run render-version
          npm run build
