name: Release StreamAwesome

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Clone Font Awesome Overwrites âœŒï¸
        uses: actions/checkout@v4
        with:
          repository: sebinside/StreamAwesome-Overwrites
          path: StreamAwesome/fonts
          ref: 'main'
          token: ${{ secrets.TOKEN }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install Dependencies ğŸ”§
        working-directory: StreamAwesome
        run: npm install

      - name: Render Version ğŸ·ï¸
        working-directory: StreamAwesome
        run: npm run render-version

      - name: Build for Latest ğŸ”¨
        working-directory: StreamAwesome
        run: npm run build
        env:
          VITE_BASE_PATH: /latest/

      - name: Deploy to Latest ğŸš€
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: StreamAwesome/dist/
          remote_path: /home/${{ secrets.USERNAME }}/html/${{ vars.TARGET }}/latest
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}

      - name: Build for Tagged Version ğŸ”¨
        working-directory: StreamAwesome
        run: npm run build
        env:
          VITE_BASE_PATH: /${{ github.ref_name }}/

      - name: Deploy to Tagged Version ğŸš€
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: StreamAwesome/dist/
          remote_path: /home/${{ secrets.USERNAME }}/html/${{ vars.TARGET }}/${{ github.ref_name }}
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}

      - name: Create Release with Notes ğŸ“
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
                --notes "**Free online version: https://streamawesome.app**" \
                --generate-notes
